export const PALETTES = [
  { name: 'Monochrome', colors: ['#000000', '#333333', '#666666', '#999999', '#CCCCCC', '#FFFFFF'] },
  { name: 'Avant-Garde', colors: ['#FF3E00', '#000000', '#FFFFFF', '#FFD700', '#0000FF'] },
  { name: 'Ethereal', colors: ['#E0C3FC', '#8EC5FC', '#F093FB', '#F5576C', '#4FACFE'] },
  { name: 'Brutalist', colors: ['#1A1A1A', '#F0F0F0', '#FF0000', '#00FF00', '#0000FF'] },
  { name: 'Organic', colors: ['#2D5A27', '#4A7C44', '#76A36F', '#A3C9A8', '#D1E8D5'] },
];

export const MOCK_PORTFOLIO: any[] = [
  {
    id: '1',
    title: 'Circadian Rhythms',
    description: 'A visualization of 30 days of sleep data, mapping deep sleep cycles to flow field turbulence.',
    tags: ['sleep', 'biometric', 'flow-field'],
    style: 'flow-field',
    dataSummary: '30 entries, 4 variables',
    timestamp: Date.now() - 86400000 * 2,
  },
  {
    id: '2',
    title: 'Market Volatility',
    description: 'Real-time stock market fluctuations transformed into a chaotic particle system.',
    tags: ['finance', 'market', 'particle-system'],
    style: 'particle-system',
    dataSummary: '500 data points',
    timestamp: Date.now() - 86400000 * 5,
  },
  {
    id: '3',
    title: 'Urban Density',
    description: 'Population data across 10 major cities represented as a geometric grid of varying intensities.',
    tags: ['demographics', 'urban', 'geometric-grid'],
    style: 'geometric-grid',
    dataSummary: '10 cities, 12 metrics',
    timestamp: Date.now() - 86400000 * 10,
  },
  {
    id: '4',
    title: 'Neural Synapse',
    description: 'Brain activity mapping during creative tasks, visualized as organic blobs.',
    tags: ['neuro', 'organic-blob'],
    style: 'organic-blob',
    dataSummary: 'EEG data stream',
    timestamp: Date.now() - 86400000 * 12,
  },
  {
    id: '5',
    title: 'Glacial Shift',
    description: 'Climate change data tracking ice shelf movement over 50 years.',
    tags: ['climate', 'noise-landscape'],
    style: 'noise-landscape',
    dataSummary: '50 years of satellite data',
    timestamp: Date.now() - 86400000 * 15,
  },
  {
    id: '6',
    title: 'Digital Pulse',
    description: 'Internet traffic patterns across global nodes during peak hours.',
    tags: ['tech', 'particle-system'],
    style: 'particle-system',
    dataSummary: 'Global node traffic',
    timestamp: Date.now() - 86400000 * 18,
  },
  {
    id: '7',
    title: 'Botanical Growth',
    description: 'Time-lapse growth data of rare flora mapped to flow fields.',
    tags: ['nature', 'flow-field'],
    style: 'flow-field',
    dataSummary: 'Growth metrics',
    timestamp: Date.now() - 86400000 * 20,
  },
  {
    id: '8',
    title: 'Acoustic Waves',
    description: 'Frequency analysis of classical compositions.',
    tags: ['music', 'geometric-grid'],
    style: 'geometric-grid',
    dataSummary: 'Audio spectrum data',
    timestamp: Date.now() - 86400000 * 22,
  },
  {
    id: '9',
    title: 'Social Echo',
    description: 'Sentiment analysis of social media trends.',
    tags: ['social', 'organic-blob'],
    style: 'organic-blob',
    dataSummary: 'Sentiment scores',
    timestamp: Date.now() - 86400000 * 25,
  },
  {
    id: '10',
    title: 'Cosmic Drift',
    description: 'Star cluster coordinates from deep space surveys.',
    tags: ['space', 'particle-system'],
    style: 'particle-system',
    dataSummary: 'Celestial coordinates',
    timestamp: Date.now() - 86400000 * 30,
  },
  {
    id: '11',
    title: 'Kinetic Energy',
    description: 'Motion capture data from contemporary dance performances.',
    tags: ['dance', 'flow-field'],
    style: 'flow-field',
    dataSummary: 'Mocap data',
    timestamp: Date.now() - 86400000 * 35,
  },
  {
    id: '12',
    title: 'Thermal Drift',
    description: 'Ocean temperature anomalies over the last decade.',
    tags: ['ocean', 'noise-landscape'],
    style: 'noise-landscape',
    dataSummary: 'Temp readings',
    timestamp: Date.now() - 86400000 * 40,
  },
  {
    id: '13',
    title: 'Atmospheric Layers',
    description: 'A study of air quality across different altitudes, visualized as translucent discs.',
    tags: ['environment', 'atmosphere', 'translucent-discs'],
    style: 'translucent-discs',
    dataSummary: 'Altitude vs AQI',
    timestamp: Date.now() - 86400000 * 45,
  },
  {
    id: '14',
    title: 'Symphonic Structure',
    description: 'The mathematical structure of a symphony mapped to an abstract score.',
    tags: ['music', 'math', 'abstract-score'],
    style: 'abstract-score',
    dataSummary: 'Note frequencies and durations',
    timestamp: Date.now() - 86400000 * 50,
  },
  {
    id: '15',
    title: 'Migratory Flow',
    description: 'Bird migration patterns across continents visualized as flowing bars.',
    tags: ['nature', 'migration', 'flowing-bars'],
    style: 'flowing-bars',
    dataSummary: 'Global tracking data',
    timestamp: Date.now() - 86400000 * 55,
  },
  {
    id: '16',
    title: 'Cellular Mandala',
    description: 'Microscopic cellular interactions visualized as organic mandalas.',
    tags: ['biology', 'micro', 'organic-mandalas'],
    style: 'organic-mandalas',
    dataSummary: 'Cell signaling data',
    timestamp: Date.now() - 86400000 * 60,
  },
  {
    id: '17',
    title: 'Network Synapse',
    description: 'A connected grid representing global server communication nodes.',
    tags: ['tech', 'network', 'connected-grid'],
    style: 'connected-grid',
    dataSummary: 'Node connectivity matrix',
    timestamp: Date.now() - 86400000 * 65,
  },
  {
    id: '18',
    title: 'Seismic Shift',
    description: 'A glitchy topographic representation of seismic activity across fault lines.',
    tags: ['geology', 'glitch', 'glitch-topography'],
    style: 'glitch-topography',
    dataSummary: 'Seismic magnitude data',
    timestamp: Date.now() - 86400000 * 70,
  }
];
